Feature/ele 365 remote collaboration users should be displayed in app header
ttab/elephant-chrome pull request #113
Opened 2024-01-23 15:40 UTC by dannelundqvist

Added awareness for "documents" and displaying avatars for remote users that have an article open. Still some issues around avatars appearing/disappearing but enough for demo purposes. Merged conflicting generalization of Avatar component into one (added more generic view agnostic variants and added support for remote user colors).

2024-01-23 22:00 UTC, gularsson approved these changes

2024-01-23 22:00 UTC, gularsson commented on src/components/AvatarGroup.tsx
> +interface AvatarGroupProps extends PropsWithChildren {}
Isn't PropsWithChildren enough as interface for the component?

2024-01-23 22:00 UTC, gularsson commented on src/components/AvatarGroup.tsx
Could this be used in AssigneeAvatar as well? :thinking:

2024-01-23 22:00 UTC, gularsson commented on src/components/Awareness.tsx
> +    <div ref={awarenessRef} className={`rounded ${visual && !!color ? 'ring' : ''} ${color}`}>
Feels like this could be clearer. `state` isn't typed as possible undefined, yet we check for length.
Maybe use `cn()` instead of ternary?

2024-01-23 22:00 UTC, gularsson commented on src/components/ViewHeader/ViewHeader.tsx
> +  const users = states.reduce<Array<{ clientId: number, data: AwarenessUserData }>>((remoteUsers, state) => {
```suggestion
  const users = states.reduce<AwarenessStates>((remoteUsers, state) => {
```

2024-01-23 22:00 UTC, gularsson commented on src/views/Planning/components/PlanDescription.tsx
> +    </Awareness>
Would prefer the previous indentation?

2024-01-23 22:05 UTC, gularsson requested changes
Clicked wrong, and accidentaly approved. 
Great feature, works good!
However there are are some changes that i suggest. Mostly due to design regressions with the Avatar component.

2024-01-24 09:58 UTC, dannelundqvist commented on src/components/AvatarGroup.tsx
Yes, that was the intention, but forgetness...

2024-01-24 11:17 UTC, gularsson approved these changes
Great! :heavy_check_mark:

2024-01-24 11:54 UTC, merged