fix: click setActive and op or noop
ttab/elephant-chrome pull request #267
Opened 2024-03-18 13:02 UTC by gularsson

2024-03-19 07:39 UTC, gularsson commented
Doesn't work :100: yet

2024-03-19 12:29 UTC, dannelundqvist requested changes
I think this might be a lot simpler if you just use an onClick handler in the capture phase (with stopPropagation() for the badge, and then a normal (bubble) phase click event handler for the row. Then a click on the badge would simply be caught before the click on the row. The result would be that neither ref or special checks on the target would be needed in the handleSetActive func. What do you think?

2024-03-19 12:48 UTC, dannelundqvist approved these changes
As we discussed, we ignore this for later.

2024-03-27 12:39 UTC, dannelundqvist approved these changes

2024-03-27 12:45 UTC, merged