feat: add AppHeader and AppMenu
ttab/elephant-chrome pull request #4
Opened 2023-10-30 12:12 UTC by gularsson

Awaiting release of `elephant-ui` v0.0.7 for Sheet component.

2023-11-01 14:10 UTC, dannelundqvist commented on src/components/ThemeSwitcher/index.tsx
Would be nice with empty line between const declaration and return statement for readability.

2023-11-01 14:16 UTC, dannelundqvist requested changes

2023-11-01 14:16 UTC, dannelundqvist commented on src/components/ViewHeader/index.tsx
Would be nice with empty line between interface and function for readability.

2023-11-01 14:16 UTC, dannelundqvist commented on src/components/index.tsx
I think it would be nice to group some of these into one folder. I.e AppMenu, AppHeader, ThemeSwitcher

2023-11-01 14:44 UTC, gularsson commented on src/components/index.tsx
`AppHeader` is a composite view which uses, `AppMenu` and `ThemeSwitcher` are never (not now) used outside of it.

2023-11-02 10:43 UTC, dannelundqvist approved these changes
Super!

2023-11-02 13:34 UTC, merged