feat: POC for saving after creation of planning
ttab/elephant-chrome pull request #424
Opened 2024-05-17 14:11 UTC by gularsson

2024-05-17 14:37 UTC, dannelundqvist requested changes

2024-05-17 14:37 UTC, dannelundqvist commented on src/lib/planning/createPlanningDocument.ts
Should we not set "todays date" instead of hardcoded value from start?

2024-05-17 14:37 UTC, dannelundqvist commented on src/lib/planning/search.ts
> +  console.log(JSON.stringify(query, null, 2))
Intentional?

2024-05-17 14:38 UTC, gularsson commented on src/lib/planning/search.ts
> +  console.log(JSON.stringify(query, null, 2))
not at all

2024-05-17 14:38 UTC, gularsson commented on src/lib/planning/createPlanningDocument.ts
yes

2024-05-20 08:50 UTC, dannelundqvist approved these changes

2024-05-20 08:58 UTC, merged