feat: add time column
ttab/elephant-chrome pull request #47
Opened 2023-12-14 09:46 UTC by gularsson

2023-12-14 10:58 UTC, dannelundqvist requested changes
Good thinking in breaking things up. We need to handle date/time a consistently and I have added a suggestion on how to make this more generic and future proof.

2023-12-14 10:58 UTC, dannelundqvist commented on src/lib/getPublishTime.ts
As all dates/times in repo/opensearch are in UTC, and we always need to display in local time, it is better to convert to (generic) Date() object immediately as this will also take timeZone into account. Then it is easier to always just convert it to displayable local format when needed. This principle will give us fewer issues.

I would like to se
```
export function getPublishTime(assignmentPublishTimes: string[]): Date | undefined {
  ...
  const date = new Date(isoString)
  if (isNaN(date.getTime()) || date.toString() === 'Invalid Date') {
    return
  }
  ...
}
```

2023-12-14 10:58 UTC, dannelundqvist commented on src/lib/datetime.ts
I think we should always require the calling party to provide a valid Date object, locale and timeZone as it will always be needed.
  
We also need to take into account that some locales use 12 hour clock and am/pm. We could add a function to datetime.ts like below:

```
function isAMPMPreferred(locale) {
  const date = new Date()
  const options = {
    hour12: true, // Use 12-hour clock (AM/PM)
  }

  try {
    const dateTimeFormatter = new Intl.DateTimeFormat(locale, options)
    const formattedDate = dateTimeFormatter.format(date)
    return formattedDate.includes('AM') || formattedDate.includes('PM')
  } catch (error) {
    return false // Default false on errors
  }
}
```

Then the code in the original function could be:
```
  return new Intl.DateTimeFormat(locale, {
    hour12: isAMPMPreferred(locale),
    hour: '2-digit',
    minute: '2-digit',
    timeZone
  }).format(date)
  ```

Though whether am/pm is preferred should probably be put into the Registry alongside locale and timeZone (and added as parameter to this function) so it is not calculated every time we display a time.

And with all these changes the original function should probably be renamed as well ;)

2023-12-18 11:46 UTC, dannelundqvist requested changes

2023-12-18 11:46 UTC, dannelundqvist commented on src/views/PlanningOverview/PlanningGridColumn.tsx
Sorry for being obnoxious here ;) but now that you've made these changes this can be a lot simpler. Function `getPublishTime()` returns  either valid date or undefined... So you can do this:

```
const assignmentDataPublish = getPublishTime(item._source['document.meta.core_assignment.data.publish'])

// Unnecessary lines...
// const startTime = assignmentDataPublish
//            ? dateToReadableTime(assignmentDataPublish, locale, timeZone)
//            : null

{!!assignmentDataPublish &&
  <div className="flex-none text-muted-foreground">
    {dateToReadableTime(assignmentDataPublish, locale, timeZone)}
  </div>
}

```

2023-12-18 12:35 UTC, gularsson commented on src/views/PlanningOverview/PlanningGridColumn.tsx
Good catch, will fix

2023-12-18 12:39 UTC, merged