Feature/ele 607 create calendar view
ttab/elephant-chrome pull request #521
Opened 2024-06-17 14:49 UTC by Victor-Lindh

2024-06-19 06:39 UTC, dannelundqvist commented on src/views/Overviews/EventsOverview/EventsHeader/Datepicker.tsx
Seems very generic, would be a good candidate to refactor into a generic component to be used elsewhere as well.

2024-06-19 07:07 UTC, dannelundqvist requested changes
A lot of ground covered. Fantastic job! Nicely structured and easy to read the code.

1. I marked out a few easy wins for refactoring to generic components. We could do it now if you think we have time, otherwise later.

2. Generally we are renaming sectors to sections. (Was hard for you to know, sorry, we should have told you). This would be good to fix now so we don't add more debt on the pile.

3. I am not really fond of putting the planning and calendar overview in a sub directory to views. They have no strong connection to each other logically or structurally. Planning detail have more in common with planning overview and calendar overview with calendar event.
I want really want us to keep the view structure completely flat as each view should be seen as independent and should be possible to open in many different situations.

2024-06-19 08:19 UTC, Victor-Lindh commented on src/views/Overviews/PlanningOverview/PlanningTable/Columns/Newsvalue.tsx
Yes, I agree. In the process of doing some more refactoring of shared components.

2024-06-19 08:47 UTC, dannelundqvist commented
> @dannelundqvist - Regarding:
> >    I really want us to keep the view structure completely flat as each view should be seen as independent and should be possible to open in many different situations.
> 
> Would it be more fitting to place an `overviews` directory in the `src/` root?

Not really. They still are separate views and should live in `src/views/` as a flat folder structure:
```
views/
   Editor/
   Error/
   Event/
   EventsOverview/
   PlanningOverview/
   Planning/
```

2024-06-19 11:28 UTC, Victor-Lindh commented on src/views/Overviews/EventsOverview/EventsTable/Columns/Sector.tsx
Fixed in new commit

2024-06-19 11:29 UTC, Victor-Lindh commented on src/views/Overviews/PlanningOverview/PlanningTable/Columns/Newsvalue.tsx
Committed and pushed.
Also, I went ahead and refactored some other components that were very generic as well.

2024-06-19 11:29 UTC, Victor-Lindh commented on src/views/Overviews/PlanningOverview/PlanningTable/Columns/Sector.tsx
Fixed in new commit

2024-06-19 11:53 UTC, Victor-Lindh commented
Pushed new commits with the above suggestions, plus some extra refactoring.

2024-06-19 12:00 UTC, Victor-Lindh commented on src/views/Overviews/EventsOverview/EventsHeader/Datepicker.tsx
Fixed in new commit

2024-06-20 06:36 UTC, dannelundqvist approved these changes
Looks a lot better now! 👍

2024-06-20 07:00 UTC, merged