Feature/ele 582 section sector picker should use real data
ttab/elephant-chrome pull request #603
Opened 2024-08-09 13:23 UTC by dannelundqvist

Replaced all uses of (hardcoded) section default values with cached data fetched from the index.

This meant we lost "color dots" for sections in tables. That data does not exist in the index. We should discuss that as a separate issue. (I left the defaults files as deprecated reference for this reason)

2024-08-12 07:36 UTC, gularsson requested changes
Over all looks good, great to finally get proper data to work with and get rid of the mocked/static data

I cant help to wonder if we shouldn't start to refactor this immediately. It's easy for me to say coming from an outside perspective :slightly_smiling_face: 

`CoreSectionProvider`, `CoreAuthorProvider` and `CoreStoryProvider` are (close to?) identical.

`useAuthor`, `useSection` and `useStory` could be one hook.
```
const { authors, section, story } = useIndexedData()
```
I dont see any point in keeping them as separate contexts or hooks in terms of rerenders or codewise.

2024-08-12 07:36 UTC, gularsson commented on src/lib/index/authors.ts
`authors.ts`, `sections.ts` and `stories.ts` are close to identical. One function? Could maybe just use `get.ts`?

2024-08-12 07:36 UTC, gularsson commented on src/lib/index/stories.ts
See `authors.ts`

2024-08-12 07:36 UTC, gularsson commented on src/datastore/contexts/CoreSectionProvider.tsx
Refactor? See PR comment at top

2024-08-12 07:36 UTC, gularsson commented on src/hooks/useSections.tsx
Refactor? See PR comment above.

2024-08-12 07:36 UTC, gularsson commented on src/views/Planning/components/PlanSection.tsx
> +  const [, setStories] = useYValue<Y.Array<unknown>>('links.core/section', {
`setStories`? Should be `setSections` right?

2024-08-12 07:36 UTC, gularsson commented on src/views/Planning/components/PlanSection.tsx
> +  const allStories = useSections().map((_) => {
`allSections`

2024-08-12 08:53 UTC, Victor-Lindh commented
Besides the points that @gularsson already brought up above, I have nothing further to add.
Looks great otherwise!

2024-08-12 08:55 UTC, dannelundqvist commented
> Over all looks good, great to finally get proper data to work with and get rid of the mocked/static data
> 
> I cant help to wonder if we shouldn't start to refactor this immediately. It's easy for me to say coming from an outside perspective 🙂

Totally agree, over the course of doing refactoring the originally messy code clearer patterns have emerged. On it. It will saves us tons of time later on.

2024-08-12 09:02 UTC, gularsson commented on src/datastore/lib/fetchSections.ts
I saw that we lost the section colors, a specific section "transformer" could augment the data received from the index.

2024-08-13 12:45 UTC, dannelundqvist commented on src/datastore/contexts/CoreSectionProvider.tsx
I will leave this as is for now.

2024-08-13 12:47 UTC, dannelundqvist commented on src/hooks/useSections.tsx
Will leave as useSections is not the same logic as useAuthors for example.

2024-08-13 13:09 UTC, merged