Feature/ele 801 show new items immediately in open views optimistic update
ttab/elephant-chrome pull request #747
Opened 2024-09-30 13:49 UTC by gularsson

Got a bit out of hand... Will start with this:
* Memoized table
* Grouping headers, newsvalue
* useFetcher and SWRProvider
* Planning and Events are fetched similarly
* Fix memoized filters
* useDeferredValue - less glitches when loading
* Fix selected row handling and navigation
* Fetch all pages/items
* Optimistic update in a separate grouping header "New items"
* Yjs document to store and track users "New items" and other data

2024-10-08 06:29 UTC, dannelundqvist commented
Seems to be a fantastic change in stability and performance. 🥳

Generally also really nice with the table group headers. Great difference! I have a few suggestions. We don't use shadows to lift information anywhere else in the system unless to elevate popovers, modals etc, I think it should be removed.

Headers in tables are traditionally (iOS) smaller in height and less prominent than the table data rows. I suggest we make it a tiny bit smaller to differentiate it more.

See attached screenshot with the upper header having the suggested changes compared to the lower.

<img width="864" alt="Skärmavbild 2024-10-08 kl  08 16 42" src="https://github.com/user-attachments/assets/77d9bfdf-33ce-435c-b1e4-4bcf465d288f">

2024-10-08 06:49 UTC, dannelundqvist requested changes

2024-10-08 06:49 UTC, dannelundqvist commented on src/components/Table/index.tsx
> +                  <span className='inline-flex items-center justify-center w-6 h-6 bg-background rounded-full ring-1 ring-gray-300 shadow-md'>
Can use `size-6` instead of `h-6 w-6`. Also suggesting to make it smaller and removing shadow (see screenshot in PR comment).

2024-10-08 06:49 UTC, dannelundqvist commented on src/components/Table/index.tsx
> +                  <span className='inline-flex items-center justify-center w-6 h-6 bg-background rounded-full ring-1 ring-gray-300 shadow-md'>
Can use `size-6` instead of `h-6 w-6`. Also suggesting to make it smaller and removing shadow (see screenshot in PR comment).

2024-10-08 06:49 UTC, dannelundqvist commented on src/lib/events/search.ts
> +                gte: params?.where?.start,
If we actually call this method without providing start or end options for the where clause, which is ok according to the interface, this search should break, won't it?.

Start and end should either be required or the range part should be added only when they are supplied.

2024-10-08 06:49 UTC, dannelundqvist commented on src/lib/index/searchIndex.ts
Why have the properties page, pages and pageSize been removed from the result interface? It is still added in the actual return value. (Which is really helpful when handling paginated results.)

2024-10-08 06:49 UTC, dannelundqvist commented on src/lib/index/plannings.ts
> +                gte: params?.where?.start,
If we actually call this method without providing start or end options for the where clause, which is ok according to the interface, this search should break, won't it?.

Start and end should either be required or the range part should be added only when they are supplied.

2024-10-08 06:49 UTC, dannelundqvist commented on src/views/EventsOverview/EventsList.tsx
> +    if (row) {
Do we really need to log selects/deselects?

2024-10-08 07:27 UTC, gularsson commented on src/lib/index/searchIndex.ts
Previous fetch only fetched the first page, leaving us with an incomplete list. Now I'm aggregating all pages to one result. I figured that information about pages and page size would be superfluous then...

2024-10-10 13:11 UTC, dannelundqvist approved these changes

2024-10-10 13:14 UTC, merged